language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
  - wget https://raw.githubusercontent.com/dinosaure/ocaml-travisci-skeleton/master/.travis-docgen.sh
script: bash -ex .travis-opam.sh
sudo: true
env:
  matrix:
  - PACKAGE="emile" OCAML_VERSION=4.06 TESTS=true
  - PACKAGE="emile" OCAML_VERSION=4.07 TESTS=true
  - PACKAGE="emile" OCAML_VERSION=4.08 TESTS=true
  - PINS="mrmime:https://github.com/mirage/mrmime.git" PACKAGE="emile" OCAML_VERSION=4.06 TESTS=true
  - PINS="mrmime:https://github.com/mirage/mrmime.git" PACKAGE="emile" OCAML_VERSION=4.07 TESTS=true
  - PINS="mrmime:https://github.com/mirage/mrmime.git" PACKAGE="emile" OCAML_VERSION=4.08 TESTS=true
